"""removed balance column

Revision ID: 30ab814da8ea
Revises: fd286217b555
Create Date: 2023-12-24 08:01:40.836983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30ab814da8ea'
down_revision: Union[str, None] = 'fd286217b555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user') as batch_op:
        batch_op.drop_column('balance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###
